import BaseComponent from './base.js';
import { promises as fs } from 'fs';
import { fileURLToPath } from 'url';
import * as sass from 'sass';
import postcss from 'postcss';
import autoprefixer from 'autoprefixer';
import sortMQ from 'postcss-sort-media-queries';
import stylelint from 'stylelint';

export default class StyleComponent extends BaseComponent {

	constructor() {
		super();
		this.description = `Lint and process style files`;
		this.dependencyGraph = new Map();
		this.reverseDependencyGraph = new Map();
	}

	async init() {
		this.files = this.utils.addEntriesByFiletypes(['.scss']);
		this.globs = await Array.fromAsync(
			this.glob(this.project.config.sassGlobPath ||
			`${this.project.path}{/${this.project.paths.src.src}/${this.project.paths.src.style},/blocks}/**/*.scss`)
		);
		await this.rebuildDependencyGraph();
		await this.process();
	}

	clearDependencyEntry(entry) {
		const existingDependencies = this.dependencyGraph.get(entry) || [];
		for (const dependency of existingDependencies) {
			const entries = this.reverseDependencyGraph.get(dependency);
			if (!entries) {
				continue;
			}

			entries.delete(entry);
			if (entries.size === 0) {
				this.reverseDependencyGraph.delete(dependency);
			}
		}

		this.dependencyGraph.delete(entry);
	}

	setDependencyEntry(entry, dependencies) {
		this.clearDependencyEntry(entry);
		this.dependencyGraph.set(entry, dependencies);

		for (const dependency of dependencies) {
			if (!this.reverseDependencyGraph.has(dependency)) {
				this.reverseDependencyGraph.set(dependency, new Set());
			}

			this.reverseDependencyGraph.get(dependency).add(entry);
		}
	}

	async rebuildDependencyGraph(entries = null) {
		const groups = entries
			? this.files.filter(group => entries.includes(group.file))
			: this.files;

		if (groups.length === 0) {
			return;
		}

		const results = await this.utils.runWithConcurrency(
			groups,
			this.utils.getComponentConcurrency('style'),
			async (group) => ({
				entry: group.file,
				dependencies: await this.utils.getImportedSASSFiles(group.file)
			})
		);

		for (const result of results) {
			this.setDependencyEntry(result.entry, result.dependencies);
		}
	}

	getAffectedEntries(changedPath) {
		const affectedEntries = new Set();

		if (this.files.some(group => group.file === changedPath)) {
			affectedEntries.add(changedPath);
		}

		for (const entry of this.reverseDependencyGraph.get(changedPath) || []) {
			affectedEntries.add(entry);
		}

		return [...affectedEntries];
	}

	async buildTheme() {
		try {
			let theme = JSON.parse(await fs.readFile(this.project.paths.theme.json));
			let themeFileData = `// This file is automatically generated from theme.json. Do not edit.\n`;
			if (theme.settings?.custom) {
				for (var customAttribute in theme.settings.custom) {
					if (customAttribute == 'dirDist') {
						themeFileData += `$themeDirDist: "${theme.settings.custom[customAttribute]}"; // --wp--custom--${this.utils.camelToDash(customAttribute)}\n`;
					} else if (['breakpoints-rem', 'breakpoint-mobile'].includes(customAttribute)) {
						// handled later in file - see 'fontSizeBase'
					} else {
						themeFileData += `$${customAttribute}: "${theme.settings.custom[customAttribute]}"; // --wp--custom--${this.utils.camelToDash(customAttribute)}\n`;
					}
				}
			}
			if (theme.settings?.layout?.contentSize) {
				themeFileData += `$global-content-size: ${theme.settings.layout.contentSize}; // --wp--style--global--content-size\n`;
			}
			if (theme.settings?.layout?.wideSize) {
				themeFileData += `$global-wide-size: ${theme.settings.layout.wideSize}; // --wp--style--global--wide-size\n`;
			}
			if (theme.styles.typography?.fontSize) {
				let fontSizeBase = theme.styles.typography.fontSize;
				themeFileData += `$font-size-base: ${theme.styles.typography.fontSize}; // --wp--preset--font-size\n`;
				if (theme.settings.custom && theme.settings.custom['breakpoints-rem']) {
					let customBreakpoints = {};
					for (var breakpoint in theme.settings.custom['breakpoints-rem']) {
						if (theme.settings.custom['breakpoints-rem'][breakpoint].toString().includes('rem')) {
							themeFileData += `$screen-${breakpoint}: ${theme.settings.custom['breakpoints-rem'][breakpoint]}; // --wp--custom--breakpoints-rem--${breakpoint}\n`;
						} else {
							themeFileData += `$screen-${breakpoint}: ${theme.settings.custom['breakpoints-rem'][breakpoint]}rem; // --wp--custom--breakpoints-rem--${breakpoint} (without 'rem')\n`;
						}
						themeFileData += `$screen-${breakpoint}-px: ${theme.settings.custom['breakpoints-rem'][breakpoint].toString().replace('rem', '') * fontSizeBase.replace('px', '')}px;\n`;
						customBreakpoints[`screen-${breakpoint}`] = `$screen-${breakpoint}`;
					}
					if (theme.settings.custom['breakpoint-mobile']) {
						themeFileData += `$mobile-breakpoint: $screen-${theme.settings.custom['breakpoint-mobile']}; // --wp--custom--breakpoint-mobile \n`;
						themeFileData += `$mobile-breakpoint-px: $screen-${theme.settings.custom['breakpoint-mobile']}-px;\n`;
						customBreakpoints[`desktop`] = `$mobile-breakpoint`;
						customBreakpoints[`mobile`] = `$mobile-breakpoint-px - 1`;
					}
					if (Object.keys(customBreakpoints).length) {
						themeFileData += `$custom-breakpoints: (\n${Object.entries(customBreakpoints).map(([key, value]) => {
							return `\t'${key}': ${value}`;
						}).join(',\n')}\n); // --wp--custom--breakpoints\n`;
					}
				}
			}
			if (theme.settings?.typography?.fontFamilies) {
				for (var fontFamily of theme.settings.typography.fontFamilies) {
					themeFileData += `$${fontFamily['slug']}: ${fontFamily['fontFamily']}; // --wp--preset--font-family--${fontFamily['slug']}\n`;
				}
			}
			if (theme.settings?.color?.palette) {
				let colorArrayString = `$colors: (\n`;
				for (var color of theme.settings.color.palette) {
					themeFileData += `$${color['slug']}: ${color['color']}; // --wp--preset--color--${color['slug']}\n`;
					colorArrayString += `\t"${color['slug']}": var(--wp--preset--color--${color['slug']}),\n`;
				}
				colorArrayString += `);\n`;
				themeFileData += colorArrayString;
			}
			if (theme.settings?.color?.gradients) {
				for (var color of theme.settings.color.gradients) {
					themeFileData += `$gradient-${color['slug']}: ${color['gradient']};\ // --wp--preset--gradient--${color['slug']}\n`;
				}
			}
			try {
				await fs.writeFile(this.project.paths.theme.scss, themeFileData);
			} catch (error) {
				this.log(null, error);
				this.log('error', `Failed to write auto-generated _theme.scss - See above error.`);
			}
		} catch (error) {
			this.log(null, error);
			this.log('error', `Failed to read theme.json - See above error.`);
		}
	}

	async build(entry, options) {
		options = Object.assign({}, {
			name: ''
		}, options);
		let outFile = `${this.project.path}/${this.project.paths.dist}/${options.name}.min.css`;
		if (options.name.startsWith('blocks/')) {
			outFile = this.project.path + '/' + options.name + '.min.css';
		}
		let entryLabel = outFile.replace(this.project.path, '');

		this.start();

		try {
			await fs.mkdir(this.path.dirname(outFile), { recursive: true });

			const sassDependencies = await this.utils.getImportedSASSFiles(entry);
			this.clearHashCache([entry, ...sassDependencies]);
			if (await this.shouldSkipBuild(entry, outFile, sassDependencies)) {
				this.end({
					itemLabel: entryLabel,
					cached: true
				});
				return true;
			}

			const compileResult = await sass.compileAsync(entry, {
				style: 'compressed',
				sourceMap: true
			});
			const postcssResult = await postcss([
				autoprefixer(),
				sortMQ()
			]).process(compileResult.css, {
				from: undefined,
				to: outFile,
				map: {
					inline: false
				}
			});
			await fs.writeFile(outFile, postcssResult.css);
			if (process.env.NODE_ENV != 'production') {
				await fs.writeFile(`${outFile}.map`, postcssResult.map.toString());
			}

			await this.updateBuildCache(entry, outFile, sassDependencies);

			this.end({
				itemLabel: entryLabel
			});
		} catch (error) {
			this.log(null, error);
			this.log('error', `Failed building ${entryLabel} - See above error.`);
			return false;
		}
	}

	async lint(targets) {
		const filesToLint = Array.isArray(targets) ? targets : [targets];
		if (filesToLint.length === 0) {
			return true;
		}

		try {
			const stylelinted = await stylelint.lint({
				configFile: this.path.resolve(this.path.dirname(fileURLToPath(import.meta.url)), '../../.stylelintrc.json'),
				formatter: 'string',
				files: filesToLint,
				customSyntax: 'postcss-scss',
				fix: true
			});

			if (stylelinted.output) {
				this.log(null, stylelinted.output);
			}

			if (stylelinted.errored) {
				if (stylelinted.report) {
					this.log(null, stylelinted.report);
				}
				return false;
			}

			return true;
		} catch (error) {
			this.log(null, error);
			this.log('error', 'Failed linting style files - See above error.');
			return false;
		}
	}

	async processEntries(entries = null, options = {}) {
		options = Object.assign({}, {
			buildTheme: true,
			lintTargets: null
		}, options);

		if (options.buildTheme) {
			await this.buildTheme();
		}

		const groups = entries
			? this.files.filter(group => entries.includes(group.file))
			: this.files;

		if (groups.length === 0) {
			return [];
		}

		const lintTargets = options.lintTargets || (entries ? entries : this.globs);
		const linted = await this.lint(lintTargets);
		if (!linted) {
			return false;
		}

		this.clearHashCache(lintTargets);

		return this.utils.runWithConcurrency(
			groups,
			this.utils.getComponentConcurrency('style'),
			group => this.build(group.file, { name: group.name })
		);
	}

	async process(entry, options) {
		return this.processEntries(entry ? [entry] : null, options);
	}

	watch() {
		this.watcher = this.chokidar.watch([
			...[this.project.paths.theme.json],
			this.globs
		], {
			...this.project.chokidarOpts
		}).on('all', async (event, path) => {
			if (!this.project.isRunning) { return; }
			try {
				if (['unlink', 'unlinkDir'].includes(event)) {
					await this.rebuildDependencyGraph();
					await this.process(null, { buildTheme: false });
					return;
				}

				const shouldBuildTheme = path == this.project.paths.theme.json;
				if (shouldBuildTheme) {
					await this.process(null, { buildTheme: true });
					return;
				}

				const affectedEntries = this.getAffectedEntries(path);

				if (affectedEntries.length > 0) {
					await this.processEntries(affectedEntries, {
						buildTheme: false,
						lintTargets: [path]
					});
					await this.rebuildDependencyGraph(affectedEntries);
					return;
				}

				await this.process(null, { buildTheme: false });
				await this.rebuildDependencyGraph();
			} catch (error) {
				this.log('error', `Failed to process styles for ${path}: ${error.message}`);
			}
		});
	}

}
